name: Test and lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    name: Build and Test (Rust + Python)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Rust
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Rust build
        run: cargo build --release

      - name: Rust lint (clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Rust tests
        run: cargo test --verbose

      # Setup Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install maturin
        run: pip install maturin

      - name: Install Python dependencies
        run: |
          pip install .[dev]

      - name: Run Ruff linter
        run: ruff check .

      - name: Run Python tests
        run: pytest
